In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

import wrangle as w

In [2]:
df, model_df = w.clean_df()

(         id  gender   age  hypertension  heart_disease  ever_married  \
 0      9046    male  67.0             0              1             1
 1     51676  female  61.0             0              0             1
 2     31112    male  80.0             0              1             1
 3     60182  female  49.0             0              0             1
 4      1665  female  79.0             1              0             1
 ...     ...     ...   ...           ...            ...           ...
 5105  18234  female  80.0             1              0             1
 5106  44873  female  81.0             0              0             1
 5107  19723  female  35.0             0              0             1
 5108  37544    male  51.0             0              0             1
 5109  44679  female  44.0             0              0             1

           work_type residence_type  avg_glucose_level   bmi  ... stroke  \
 0           private          urban             228.69  36.6  ...      1
 1     self-employed          rural             202.21  28.9  ...      1
 2           private          rural             105.92  32.5  ...      1
 3           private          urban             171.23  34.4  ...      1
 4     self-employed          rural             174.12  24.0  ...      1
 ...             ...            ...                ...   ...  ...    ...
 5105        private          urban              83.75  28.9  ...      0
 5106  self-employed          urban             125.20  40.0  ...      0
 5107  self-employed          rural              82.99  30.6  ...      0
 5108        private          rural             166.29  25.6  ...      0
 5109       govt_job          urban              85.28  26.2  ...      0

       gender_male  work_type_govt_job  work_type_never_worked  \
 0               1                   0                       0
 1               0                   0                       0
 2               1                   0                       0
 3               0                   0                       0
 4               0                   0                       0
 ...           ...                 ...                     ...
 5105            0                   0                       0
 5106            0                   0                       0
 5107            0                   0                       0
 5108            1                   0                       0
 5109            0                   1                       0

       work_type_private  work_type_self-employed  residence_type_urban  \
 0                     1                        0                     1
 1                     0                        1                     0
 2                     1                        0                     0
 3                     1                        0                     1
 4                     0                        1                     0
 ...                 ...                      ...                   ...
 5105                  1                        0                     1
 5106                  0                        1                     1
 5107                  0                        1                     0
 5108                  1                        0                     0
 5109                  0                        0                     1

       smoking_status_formerly smoked  smoking_status_never smoked  \
 0                                  1                            0
 1                                  0                            1
 2                                  0                            1
 3                                  0                            0
 4                                  0                            1
 ...                              ...                          ...
 5105                               0                            1
 5106                               0                            1
 5107                               0                            1
 5108                               1                            0
 5109                               0                            0

       smoking_status_smokes
 0                         0
 1                         0
 2                         0
 3                         1
 4                         0
 ...                     ...
 5105                      0
 5106                      0
 5107                      0
 5108                      0
 5109                      0

 [5109 rows x 21 columns],
        age  hypertension  heart_disease  ever_married  avg_glucose_level  \
 0     67.0             0              1             1             228.69
 1     61.0             0              0             1             202.21
 2     80.0             0              1             1             105.92
 3     49.0             0              0             1             171.23
 4     79.0             1              0             1             174.12
 ...    ...           ...            ...           ...                ...
 5105  80.0             1              0             1              83.75
 5106  81.0             0              0             1             125.20
 5107  35.0             0              0             1              82.99
 5108  51.0             0              0             1             166.29
 5109  44.0             0              0             1              85.28

        bmi  stroke  gender_male  work_type_govt_job  work_type_never_worked  \
 0     36.6       1            1                   0                       0
 1     28.9       1            0                   0                       0
 2     32.5       1            1                   0                       0
 3     34.4       1            0                   0                       0
 4     24.0       1            0                   0                       0
 ...    ...     ...          ...                 ...                     ...
 5105  28.9       0            0                   0                       0
 5106  40.0       0            0                   0                       0
 5107  30.6       0            0                   0                       0
 5108  25.6       0            1                   0                       0
 5109  26.2       0            0                   1                       0

       work_type_private  work_type_self-employed  residence_type_urban  \
 0                     1                        0                     1
 1                     0                        1                     0
 2                     1                        0                     0
 3                     1                        0                     1
 4                     0                        1                     0
 ...                 ...                      ...                   ...
 5105                  1                        0                     1
 5106                  0                        1                     1
 5107                  0                        1                     0
 5108                  1                        0                     0
 5109                  0                        0                     1

       smoking_status_formerly smoked  smoking_status_never smoked  \
 0                                  1                            0
 1                                  0                            1
 2                                  0                            1
 3                                  0                            0
 4                                  0                            1
 ...                              ...                          ...
 5105                               0                            1
 5106                               0                            1
 5107                               0                            1
 5108                               1                            0
 5109                               0                            0

       smoking_status_smokes
 0                         0
 1                         0
 2                         0
 3                         1
 4                         0
 ...                     ...
 5105                      0
 5106                      0
 5107                      0
 5108                      0
 5109                      0

 [5109 rows x 16 columns])